### ISSUE TITLE
Client side error: .env has no default export

### ISSUE THREAD

**Issue by coooolers** [alexitaylor/angular-graphql-nestjs-postgres-starter-kit#31]
When I run npm start at the client side, I get this error:

ERROR in environments/environment.ts:6:8 - error TS1192: Module '"/home/Project/tp/client/src/environments/.env"' has no default export.

6 import env from './.env';
         ~~~
environments/environment.prod.ts:2:8 - error TS1192: Module '"/home/Project/tp/client/src/environments/.env"' has no default export.

2 import env from './.env';
         ~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.

**Comment by coooolers** [comment]
But the contents of the .env file seem to be correct:

export const env: { [s: string]: (string | null); } = {
  'npm_package_version': '1.0.0'
};

**Comment by alexitaylor** [comment]
Fixed with PR #33 

cc: @coooolers

**Comment by imomin** [comment]
I did following and it worked for me.
`import {env} from './.env';`

**Comment by coooolers** [comment]
Thanks
